apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: observability-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/part-of: observability-operator
  name: observability-operatorwxxy
spec:
  port:
    targetPort: 8079
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: observability-operator
    weight: 100
status: {}
