apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: observability-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/part-of: observability-operator
  name: observability-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: observability-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: observability-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mleonova-tenant/observability-operator/observability-operator@sha256:af4e62a29f79d8968ee78b9796944ee9b0d91f1495c6be016c676189adf1eba7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8079
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
