apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: observability-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/part-of: observability-operator
  name: observability-operator
spec:
  ports:
  - port: 8079
    targetPort: 8079
  selector:
    app.kubernetes.io/instance: observability-operator
status:
  loadBalancer: {}
